"""add url in news

Revision ID: 8aa1a4cbd5bc
Revises: a0759e297410
Create Date: 2025-03-17 17:33:40.794488

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8aa1a4cbd5bc"
down_revision: Union[str, None] = "a0759e297410"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("news", sa.Column("url", sa.String(length=128), nullable=False))
    op.drop_column("news", "published_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "news",
        sa.Column(
            "published_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("news", "url")
    # ### end Alembic commands ###
