"""change length for url field in News model

Revision ID: ce0b1591f5b9
Revises: 562e39bce886
Create Date: 2025-03-17 21:21:12.233303

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ce0b1591f5b9"
down_revision: Union[str, None] = "562e39bce886"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "news",
        "url",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.Text(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "news",
        "url",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=128),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
