"""add was_sent to News model

Revision ID: f6fcbb9351d0
Revises: ce0b1591f5b9
Create Date: 2025-03-18 14:14:38.196928

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6fcbb9351d0"
down_revision: Union[str, None] = "ce0b1591f5b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("news", sa.Column("was_sent", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news", "was_sent")
    # ### end Alembic commands ###
